package com.mbg.po;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.dept_id
     *
     * @mbg.generated Wed May 08 13:09:51 CST 2019
     */
    private Integer dept_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.dept_name
     *
     * @mbg.generated Wed May 08 13:09:51 CST 2019
     */
    private String dept_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.dept_id
     *
     * @return the value of tbl_dept.dept_id
     *
     * @mbg.generated Wed May 08 13:09:51 CST 2019
     */
    public Integer getDept_id() {
        return dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.dept_id
     *
     * @param dept_id the value for tbl_dept.dept_id
     *
     * @mbg.generated Wed May 08 13:09:51 CST 2019
     */
    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.dept_name
     *
     * @return the value of tbl_dept.dept_name
     *
     * @mbg.generated Wed May 08 13:09:51 CST 2019
     */
    public String getDept_name() {
        return dept_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.dept_name
     *
     * @param dept_name the value for tbl_dept.dept_name
     *
     * @mbg.generated Wed May 08 13:09:51 CST 2019
     */
    public void setDept_name(String dept_name) {
        this.dept_name = dept_name == null ? null : dept_name.trim();
    }
}